version: '3.8'

services:
  bot_p:
    build: .
    command: python bots/BOT_P.py
    env_file: .env
    restart: unless-stopped
    mem_limit: 128m
    cpus: 0.3
    volumes:
      - ./logs:/app/logs
    networks:
      - bots-network

  bot_pr:
    build: .
    command: python bots/BOT_PR.py
    env_file: .env
    restart: unless-stopped
    mem_limit: 128m
    cpus: 0.3
    volumes:
      - ./logs:/app/logs
    depends_on:
      - bot_p
    networks:
      - bots-network

  bot_inv:
    build: .
    command: python bots/BOT_Inv.py
    env_file: .env
    restart: unless-stopped
    mem_limit: 128m
    cpus: 0.3
    volumes:
      - ./logs:/app/logs
    depends_on:
      - bot_p
    networks:
      - bots-network

  bot_str:
    build: .
    command: python bots/BOT_Str.py
    env_file: .env
    restart: unless-stopped
    mem_limit: 128m
    cpus: 0.3
    volumes:
      - ./logs:/app/logs
    depends_on:
      - bot_p
    networks:
      - bots-network

  bot_ocenka:
    build: .
    command: python bots/BOT_Ocenka.py
    env_file: .env
    restart: unless-stopped
    mem_limit: 128m
    cpus: 0.3
    volumes:
      - ./logs:/app/logs
    depends_on:
      - bot_p
    networks:
      - bots-network

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    mem_limit: 64m
    cpus: 0.2
    depends_on:
      - bot_p
      - bot_pr
      - bot_inv
      - bot_str
      - bot_ocenka
    networks:
      - bots-network

networks:
  bots-network:
    driver: bridge