# Docker Compose конфигурация для веб-сайта мониторинга ботов
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: real-estate-web
    ports:
      - "8080:80"
    restart: unless-stopped
    
    # Ограничения ресурсов
    mem_limit: 32m
    mem_reservation: 16m
    cpus: 0.1
    
    # Переменные окружения
    environment:
      - NGINX_WORKER_PROCESSES=auto
      - NGINX_WORKER_CONNECTIONS=1024
    
    # Мониторинг здоровья
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Логирование
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Сеть
    networks:
      - web-network
    
    # Метки для мониторинга
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`)"
      - "traefik.http.services.web.loadbalancer.server.port=80"
      - "com.docker.compose.service=web"
      - "com.docker.compose.project=real-estate-bots"

networks:
  web-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.driver.mtu: "1500"
    ipam:
      config:
        - subnet: 172.20.0.0/16